from ex0.Card import Card

class  ArtifactCard (Card):
    def __init__(self, name: str, cost: int, rarity: str, durability: int, effect: str): ...
    
    def play(self, game_state: dict) -> dict: ...
    
    def activate_ability(self) -> dict: ...