from abc import ABC, abstractmethod

class Rankable (ABC):
    
    def calculate_rating(self) -> int: ...
    def update_wins(self, wins: int) -> None: ...
    def update_losses(self, losses: int) -> None: ...
    def get_rank_info(self) -> dict: ...